apiVersion: v1
imagePullSecrets:
- name: dkube-dockerhub-secret
kind: ServiceAccount
metadata:
  name: argo
  namespace: modelmonitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    ksonnet.io/component: mm-argo
  name: mm-argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: modelmonitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
  namespace: modelmonitor
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-binding
  namespace: modelmonitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-role
subjects:
  - kind: ServiceAccount
    name: argo
---
apiVersion: v1
data:
  config: |
    artifactRepository:
      archiveLogs: false
    instanceID: modelmonitor
kind: ConfigMap
metadata:
  labels:
    ksonnet.io/component: mm-argo
  name: mm-workflow-controller-configmap
  namespace: modelmonitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ksonnet.io/component: mm-argo
  name: mm-workflow-controller
  namespace: modelmonitor
spec:
  selector:
    matchLabels:
      app: mm-workflow-controller
  template:
    metadata:
      labels:
        app: mm-workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - mm-workflow-controller-configmap
        - --executor-image
        - argoproj/argoexec:v3.1.13
        - --namespaced
        command:
        - workflow-controller
        env:
        - name: LEADER_ELECTION_IDENTITY
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: docker.io/argoproj/workflow-controller:v3.1.13
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6060
          initialDelaySeconds: 90
          periodSeconds: 60
          timeoutSeconds: 30
        name: mm-workflow-controller
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 6060
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
      dnsPolicy:  ClusterFirst
      schedulerName: default-scheduler
      nodeSelector: NODE_SELECTOR
      serviceAccountName: argo
---
