apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: dkube-controller-master
    version: verTag
  name: dkube-controller-master-verTag
  namespace: dkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkube-controller-master
      version: verTag
  serviceName: dkube-controller-master-headless
  template:
    metadata:
      labels:
        app: dkube-controller-master
        version: verTag
    spec:
      containers:
      - env:
        - name: DKUBE_MOUNT_PATH
          value: /home/dkube/d3s
        - name: DKUBE_REGISTRY
          value: dkubeRegistryPath
        - name: DKUBE_REGISTRY_UNAME
          value: dkubeRegistryUname
        - name: DKUBE_REGISTRY_PASSWD
          value: dkubeRegistryPasswd
        - name: DKUBE_SERVICE_ACCOUNT
          value: dkube
        - name: RDMA_ENABLED
          value: "false"
        - name: NFS_SERVER
          value: nfsServer
        - name: NFS_BASE_PATH
          value: nfsBasePath
        - name: DKUBE_APISERVER_ROLE
          value: master
        - name: CEPH_MONITORS
          value: 'cephMonitors'
        - name: DKUBE_STORAGE_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: dkube-installer
              key: DKUBE_STORAGE_PROVIDER
        - name: DKUBE_CLUSTER
          value: dkubeClusterType
        - name: MODEL_REGISTRY
          value: modelRegistry
        image: dkubeApiServerImage
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 5000
          name: dkube-d3api
          protocol: TCP
        securityContext:
          procMount: Default
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/dkube/d3s
          name: store
        - mountPath: /var/run/docker.sock
          name: docker
        - mountPath: /var/log/dkube
          name: dkube-logs
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dkubeDockerSecret
      nodeSelector: NODE_SELECTOR
      restartPolicy: Always
      serviceAccount: dkube
      serviceAccountName: dkube
      volumes:
      - name: store
        cephfs:
          monitors: cephMonitors
          path: /dkube
          user: admin
          secretRef:
            name: ceph-secret
      - name: dkube-logs
        cephfs:
          monitors: cephMonitors
          path: /dkube/system/logs/dkube
          user: admin
          secretRef:
            name: ceph-secret
      - hostPath:
          path: /var/run/docker.sock
        name: docker
