---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ksonnet.io/component: minio
  name: dkube-minio-pvc
  namespace: dkube
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 75Gi
  storageClassName: ""
  volumeName: dkube-minio-pv
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
        apiVersion: ambassador/v0
        kind: Mapping
        name: dkube_minio
        prefix: /minio/
        rewrite: /
        timeout_ms: 600000
        service: dkube-minio-server:9000
  labels:
    ksonnet.io/component: minio
  name: dkube-minio-server
  namespace: dkube
spec:
  ports:
  - nodePort: 32223
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: minio
    ksonnet.io/component: minio
  name: dkube-minio-server
  namespace: dkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          value: dkube
        - name: MINIO_SECRET_KEY
          value: minioSecretKey
        image: minio/minio:RELEASE.2018-12-13T02-04-19Z
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: 5Gi
        volumeMounts:
        - mountPath: /storage
          name: storage
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      nodeSelector: NODE_SELECTOR
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: dkube-minio-pvc
