apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  dkube.ai: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-deployment
  namespace: knative-serving
data:
  registriesSkippingTagResolving: "index.docker.io"
  progressDeadline: "10m"

