---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: dkube-controller-worker
    version: verTag
  name: dkube-controller-worker-verTag
  namespace: dkube
spec:
  selector:
    matchLabels:
      app: dkube-controller-worker
      version: verTag
  template:
    metadata:
      labels:
        app: dkube-controller-worker
        version: verTag
    spec:
      containers:
      - env:
        - name: DKUBE_MOUNT_PATH
          value: /home/dkube/d3s
        - name: DKUBE_REGISTRY
          value: dkubeRegistryPath
        - name: DKUBE_REGISTRY_UNAME
          value: dkubeRegistryUname
        - name: DKUBE_REGISTRY_PASSWD
          value: dkubeRegistryPasswd
        - name: DKUBE_SERVICE_ACCOUNT
          value: dkube
        - name: RDMA_ENABLED
          value: "false"
        - name: NFS_SERVER
          value: nfsServer
        - name: NFS_BASE_PATH
          value: nfsBasePath
        - name: CEPH_MONITORS
          value: 'cephMonitors'
        - name: DKUBE_STORAGE_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: dkube-installer
              key: DKUBE_STORAGE_PROVIDER
        - name: DKUBE_APISERVER_ROLE
          value: worker
        - name: DKUBE_CLUSTER
          value: dkubeClusterType
        - name: MODEL_REGISTRY
          value: modelRegistry
        image: dkubeApiServerImage
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 5000
          name: dkube-d3api
          protocol: TCP
        securityContext:
          procMount: Default
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/dkube/d3s
          name: store
        - mountPath: /var/run/docker.sock
          name: docker
        - mountPath: /var/log/dkube
          name: dkube-logs
      - image: dkubeDownloaderImage
        imagePullPolicy: IfNotPresent
        name: sidecar
        securityContext:
          procMount: Default
          runAsUser: 0
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dkubeDockerSecret
      restartPolicy: Always
      serviceAccount: dkube
      serviceAccountName: dkube
      volumes:
      - name: store
        cephfs:
          monitors: cephMonitors
          path: /dkube
          user: admin
          secretRef:
            name: ceph-secret
      - name: dkube-logs
        cephfs:
          monitors: cephMonitors
          path: /dkube/system/logs/dkube
          user: admin
          secretRef:
            name: ceph-secret
      - hostPath:
          path: /var/run/docker.sock
        name: docker
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: dkube-ext
    version: verTag
  name: dkube-exporter-verTag
  namespace: dkube
spec:
  selector:
    matchLabels:
      app: dkube-ext
      version: verTag
  template:
    metadata:
      labels:
        app: dkube-ext
        version: verTag
    spec:
      containers:
      - env:
        - name: MYNODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: dkubeExtImage
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 9401
          name: http-metrics
          protocol: TCP
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /usr/local/nvidia/lib64
          name: nvidia-lib
        - mountPath: /var/run/docker.sock
          name: docker
      serviceAccountName: dkube
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      imagePullSecrets:
      - name: dkubeDockerSecret
      volumes:
      - hostPath:
          path: /usr/lib64/nvidia
        name: nvidia-lib
      - hostPath:
          path: /var/run/docker.sock
        name: docker
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: dkube-metric-collector
    version: verTag
  name: dkube-log-processor-verTag
  namespace: dkube
spec:
  selector:
    matchLabels:
      k8s-app: dkube-metric-collector
      version: verTag
  template:
    metadata:
      labels:
        k8s-app: dkube-metric-collector
        version: verTag
    spec:
      containers:
      - image: fluentdImage
        imagePullPolicy: IfNotPresent
        name: main
        securityContext:
          procMount: Default
          runAsUser: 0
        volumeMounts:
        - mountPath: LOG_PATH
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluentd/etc/
          name: dkube-metric-collector
          readOnly: true
        - mountPath: /var/log
          name: varlog
      - image: fluentdImage
        imagePullPolicy: IfNotPresent
        name: sidecar
        securityContext:
          procMount: Default
          runAsUser: 0
        volumeMounts:
        - mountPath: LOG_PATH
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluentd/etc/
          name: dkube-log-collector
          readOnly: true
        - mountPath: /var/log
          name: varlog
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: dkube
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - configMap:
          defaultMode: 420
          name: dkube-log-collector
        name: dkube-log-collector
      - hostPath:
          path: LOG_PATH
        name: varlibdockercontainers
      - configMap:
          defaultMode: 420
          name: dkube-metric-collector
        name: dkube-metric-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dkube-auth
    version: verTag
  name: dkube-auth-server-verTag
  namespace: dkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkube-auth
      version: verTag
  template:
    metadata:
      labels:
        app: dkube-auth
        version: verTag
      name: d3auth
      namespace: dkube
    spec:
      containers:
      - command:
        - /opt/dkube/dex
        - serve
        - /etc/dex/cfg/config.yaml
        image: dkubeAuthImage
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 5556
          name: dex-s
          protocol: TCP
        securityContext:
          procMount: Default
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/dex/cfg
          name: auth-cm
      - image: dkubeAuthImage
        imagePullPolicy: IfNotPresent
        name: sidecar
        command: ["bash", "-c", "sleep 30; /opt/dkube/d3"]
        env:
        - name: DKUBE_CLUSTER
          value: dkubeClusterType
        ports:
        - containerPort: 3001
          name: authn
          protocol: TCP
        volumeMounts:
        - mountPath: /var/log/dkube
          name: dkube-logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dkubeDockerSecret
      nodeSelector: NODE_SELECTOR
      restartPolicy: Always
      serviceAccount: dkube
      serviceAccountName: dkube
      volumes:
      - configMap:
          defaultMode: 420
          name: dkube-auth-config
        name: auth-cm
      - name: dkube-logs
        cephfs:
          monitors: cephMonitors
          path: /dkube/system/logs/dkube
          user: admin
          secretRef:
            name: ceph-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: verTag
  name: dkube-db-server-verTag
  namespace: dkube
spec:
  selector:
    matchLabels:
      app: dkube-db-server
      version: verTag
  template:
    metadata:
      labels:
        app: dkube-db-server
        version: verTag
    spec:
      containers:
      - command:
        - etcd
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://0.0.0.0:2379
        - --data-dir=/var/lib/etcd
        - --force-new-cluster
        - --election-timeout=30000
        image: k8s.gcr.io/etcd-amd64:3.1.12
        imagePullPolicy: IfNotPresent
        name: main
        volumeMounts:
        - mountPath: /var/lib/etcd
          name: etcd-data
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      nodeSelector: NODE_SELECTOR
      volumes:
      - name: etcd-data
        persistentVolumeClaim:
          claimName: dkube-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dkube-tools
    version: verTag
  name: dkube-inf-doc-server-verTag
  namespace: dkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkube-tools
      version: verTag
  template:
    metadata:
      labels:
        app: dkube-tools
        version: verTag
    spec:
      containers:
      - image: dkubeInferenceImage
        imagePullPolicy: IfNotPresent
        name: main
      - image: dkubeDocsImage
        imagePullPolicy: IfNotPresent
        name: sidecar
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dkubeDockerSecret
      nodeSelector: NODE_SELECTOR
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dkube-operator-proxy
    version: verTag
  name: dkube-operator-api-proxy-verTag
  namespace: dkube
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dkube-operator-proxy
      version: verTag
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dkube-operator-proxy
        version: verTag
    spec:
      containers:
      - image: dfabProxyImage
        imagePullPolicy: IfNotPresent
        name: main
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dkubeDockerSecret
      nodeSelector: NODE_SELECTOR
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dkube-storage-exporter
    version: verTag
  name: dkube-storage-exporter-verTag
  namespace: dkube
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dkube-storage-exporter
      version: verTag
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dkube-storage-exporter
        version: verTag
    spec:
      containers:
      - env:
        - name: DKUBE_STORAGE_PATH
          value: /opt/dkube-storage
        image: storageExporterImage
        imagePullPolicy: IfNotPresent
        name: main
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/dkube-storage
          name: storage
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dkubeDockerSecret
      nodeSelector: NODE_SELECTOR
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage
        cephfs:
          monitors: cephMonitors
          path: /
          user: admin
          secretRef:
            name: ceph-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dkube-d3watcher
    version: verTag
  name: dkube-watcher-verTag
  namespace: dkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkube-d3watcher
      version: verTag
  template:
    metadata:
      labels:
        app: dkube-d3watcher
        version: verTag
    spec:
      containers:
      - env:
        - name: DKUBE_SERVICE_ACCOUNT
          value: dkube
        image: dkubeWatcherImage
        imagePullPolicy: IfNotPresent
        name: main
        securityContext:
          procMount: Default
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/dkube
          name: dkube-logs-host
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dkubeDockerSecret
      nodeSelector: NODE_SELECTOR
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: dkube
      serviceAccountName: dkube
      volumes:
      - hostPath:
          path: /var/log/dkube
          type: DirectoryOrCreate
        name: dkube-logs-host
