apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dkube-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: dkube-installer-sa
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dkube-installer-sa
  namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkube-installer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkube-installer
  template:
    metadata:
      labels:
        app: dkube-installer
    spec:
      serviceAccountName: dkube-installer-sa
      containers:
      - name: dkube-installer
        image: dkube-installer:v1
        imagePullPolicy: IfNotPresent
        env:
          - name: GITHUB_TOKEN
            value: "14f74455887f83d4ec780d43f4a510de2fc21074"
          - name: CLIENT_ID 
            value: "e48e19a508229c0617ad"
          - name: CLIENT_SECRET
            value: "fa67ef01778859f935d7a90dfc40b8c6f8f7c27a"
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube/config
        - name: dkubestore
          mountPath: /var/dkube

      volumes:
      - name: kubeconfig
        hostPath:
          path: /home/dkube/.kube/config
        
      - name: dkubestore
        hostPath:
          path: /var/dkube
          type: Directory


