apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dkube-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: dkube-installer-sa
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dkube-installer-sa
  namespace: kube-system
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJsdWNpZmVyMDAxIiwicGFzc3dvcmQiOiJsdWNpZmVyQGRrdWJlIiwiZW1haWwiOiJvY2RsZ2l0QG9uZWNvbnZlcmdlbmNlLmNvbSIsImF1dGgiOiJiSFZqYVdabGNqQXdNVHBzZFdOcFptVnlRR1JyZFdKbCJ9fX0=
kind: Secret
metadata:
  name: dkube-dockerhub-secret
  namespace: kube-system
type: kubernetes.io/dockerconfigjson

--- 
apiVersion: v1
kind: Pod
metadata: 
  name: dkube-installer
  namespace: kube-system
spec: 
  restartPolicy: Never
  imagePullSecrets:
  - name: dkube-dockerhub-secret
  containers: 
    - 
      env: 
        - 
          name: GITHUB_TOKEN
          value: df32a498bd0e85f08396bfdb0afc4ecf6270186d
        - 
          name: CLIENT_ID
          value: 9e42bc01e28d2c4f3f3f
        - 
          name: CLIENT_SECRET
          value: 13c69821cd1e24ad0e5e9b0a85f8e6a83d52d637
      image: "ocdr/dkube-installer:v1"
      imagePullPolicy: IfNotPresent
      name: dkube-installer
      volumeMounts: 
        - 
          mountPath: /root/.kube/config
          name: kubeconfig
        - 
          mountPath: /var/dkube
          name: dkubestore
      command:
        - sleep
        - infinity
        #- /usr/local/bin/install.sh
        #- install

  serviceAccountName: dkube-installer-sa
  volumes: 
    - 
      hostPath: 
        path: /etc/kubernetes/admin.conf
      name: kubeconfig
    - 
      hostPath: 
        path: /var/dkube
        type: Directory
      name: dkubestore

