---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  name: dkube-webapp
  namespace: dkube-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkube-webapp
      inference: webapp
  template:
    metadata:
      labels:
        app: dkube-webapp
        inference: webapp
    spec:
      containers:
      - image: ocdr/dkube-d3inf:1.2.1
        imagePullPolicy: IfNotPresent
        name: inference
        ports:
        - containerPort: 8000
      - image: ocdr/dkube-docs:1.2.1
        name: docs
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: dkube-dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  dkube_docs
      prefix: /
      rewrite: /
      timeout_ms: 600000
      service: dkube-docs:8888
      cors:
       origins: "*"
       methods: "*"
       headers: "*"
  name: dkube-docs
  namespace: dkube-tools
spec:
  ports:
  - name: serve
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    inference: webapp
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  dkube_webapp
      prefix: /inference
      rewrite: /inference
      timeout_ms: 600000
      service: dkube-webapp:8000
      cors:
       origins: "*"
       methods: "*"
       headers: "*"
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  dkube_webapp_predict
      prefix: /predict
      rewrite: /predict
      timeout_ms: 600000
      service: dkube-webapp:8000
      cors:
       origins: "*"
       methods: "*"
       headers: "*"
  name: dkube-webapp
  namespace: dkube-tools
spec:
  ports:
  - name: serve
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    inference: webapp
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador-1-2
  namespace: dkube-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ambassador
  template:
    metadata:
      labels:
        service: ambassador
      namespace: dkube-tools
    spec:
      containers:
      - env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: "false"
        image: quay.io/datawire/ambassador:0.53.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: ambassador
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
            scheme: HTTP
        resources:
          limits:
            cpu: "1"
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
      nodeSelector:
        d3.nodetype: dkube
      restartPolicy: Always
      serviceAccount: ambassador
      serviceAccountName: ambassador
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador
  namespace: dkube-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ambassador
  namespace: dkube-tools
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
  - patch
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
data:
  tls.crt: Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOiAxNTMgKDB4OTkpCiAgICAgICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICBJc3N1ZXI6IEM9SU4sIFNUPVRlbGFuZ2FuYSwgTD1IeWRlcmFiYWQsIE89b25lY29udmVyZ2VuY2UsIENOPWRrdWJlLCBPVT1OaWwvZW1haWxBZGRyZXNzPU5pbAogICAgICAgIFZhbGlkaXR5CiAgICAgICAgICAgIE5vdCBCZWZvcmU6IEFwciAgMyAxMToxNDowMCAyMDE5IEdNVAogICAgICAgICAgICBOb3QgQWZ0ZXIgOiBBcHIgIDIgMTE6MTQ6MDAgMjAyMCBHTVQKICAgICAgICBTdWJqZWN0OiBDPUlOLCBTVD1UZWxhbmdhbmEsIE89b25lY29udmVyZ2VuY2UsIE9VPU5pbCwgQ049ZGt1YmUvZW1haWxBZGRyZXNzPU5pbAogICAgICAgIFN1YmplY3QgUHVibGljIEtleSBJbmZvOgogICAgICAgICAgICBQdWJsaWMgS2V5IEFsZ29yaXRobTogcnNhRW5jcnlwdGlvbgogICAgICAgICAgICAgICAgUlNBIFB1YmxpYy1LZXk6ICgyMDQ4IGJpdCkKICAgICAgICAgICAgICAgIE1vZHVsdXM6CiAgICAgICAgICAgICAgICAgICAgMDA6ZTA6NTU6ZjM6YzI6YTY6OTU6OWI6Yzk6ODc6MjY6MTQ6MzI6YWQ6NDA6CiAgICAgICAgICAgICAgICAgICAgOGM6MDE6MDQ6MTc6ZjI6MjQ6Yjg6ZDk6ZGM6MmU6MWU6YWE6NGU6M2I6OTc6CiAgICAgICAgICAgICAgICAgICAgZmI6MmY6NTU6NDY6ODM6ZjQ6OTQ6OWQ6NTQ6ZTI6NTA6NTU6NmM6ZWY6ZjY6CiAgICAgICAgICAgICAgICAgICAgMzk6NTY6MWQ6NDg6ZmI6M2Q6ODI6OGE6ZWY6MTE6N2Q6YWE6NmQ6NTA6MmE6CiAgICAgICAgICAgICAgICAgICAgYTA6M2U6MzA6ZGQ6YWE6NmQ6NjQ6MjQ6ZmE6YTQ6ODk6NDk6Yzg6NTY6YzE6CiAgICAgICAgICAgICAgICAgICAgNjA6YTg6MmM6NWE6NTI6YTQ6ZDU6YjY6YjM6YWU6YWU6ODA6NWM6ZmY6MjM6CiAgICAgICAgICAgICAgICAgICAgYzc6ZTI6YjU6OGU6OTk6ZmI6MWQ6NTA6MTU6Nzk6YWY6NjI6YWU6Nzg6MmM6CiAgICAgICAgICAgICAgICAgICAgYjU6ZmI6M2E6MTY6ZmQ6ZGU6YmI6YWI6MTc6OTk6MWE6NGI6N2U6Nzg6NTI6CiAgICAgICAgICAgICAgICAgICAgOTA6Zjg6MGM6NzM6NzA6YTE6MGI6NjU6NGE6NGQ6YTM6MWY6YmI6MmU6ZDU6CiAgICAgICAgICAgICAgICAgICAgYzU6MTk6OTg6NGQ6MWI6ODA6Y2M6YzY6MmU6MWI6OTk6MWM6YTc6OGQ6MDA6CiAgICAgICAgICAgICAgICAgICAgZmY6YjE6ZTg6NTc6YmI6ZmE6NWU6NGY6Y2U6NGY6ZTQ6NmE6Y2Y6NDI6Njg6CiAgICAgICAgICAgICAgICAgICAgMGM6OGE6ZWE6ODk6ZjY6ZmY6Mzk6ZDU6N2M6YTc6M2E6NGY6ODE6NTI6NDI6CiAgICAgICAgICAgICAgICAgICAgNzc6M2I6NDU6NDQ6YjE6YWY6Mjk6Yzc6ZDA6NWI6OTI6Yzc6NjM6ZDQ6Mjg6CiAgICAgICAgICAgICAgICAgICAgMjE6ZDY6ZDI6ODg6MTQ6OGU6MTU6N2M6YTI6Y2E6MzA6ZGU6MDY6MjY6NmI6CiAgICAgICAgICAgICAgICAgICAgZjA6YWE6MzI6MzI6NWI6MzA6NTI6ZmE6NmM6YTA6MzQ6ZTY6NDc6MDg6MDE6CiAgICAgICAgICAgICAgICAgICAgYTc6N2Q6YjM6NGY6Yzg6NDg6Nzk6OGU6ZWQ6ZTk6YjE6ZDk6NDM6OTQ6OGM6CiAgICAgICAgICAgICAgICAgICAgNDY6ZDg6MTI6MTg6YmU6MTg6MWU6Mjc6MDc6Yzg6MDA6MzA6NTk6Yjc6ZTU6CiAgICAgICAgICAgICAgICAgICAgYjI6OTMKICAgICAgICAgICAgICAgIEV4cG9uZW50OiA2NTUzNyAoMHgxMDAwMSkKICAgICAgICBYNTA5djMgZXh0ZW5zaW9uczoKICAgICAgICAgICAgWDUwOXYzIEJhc2ljIENvbnN0cmFpbnRzOiAKICAgICAgICAgICAgICAgIENBOkZBTFNFCiAgICAgICAgICAgIE5ldHNjYXBlIENvbW1lbnQ6IAogICAgICAgICAgICAgICAgT3BlblNTTCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUKICAgICAgICAgICAgWDUwOXYzIFN1YmplY3QgS2V5IElkZW50aWZpZXI6IAogICAgICAgICAgICAgICAgN0Q6QjE6NkY6OTQ6M0I6Nzc6Rjg6ODE6MUY6Qzk6OUM6RUE6NTA6MzE6Q0Y6NEU6NTg6NzE6QjM6MEIKICAgICAgICAgICAgWDUwOXYzIEF1dGhvcml0eSBLZXkgSWRlbnRpZmllcjogCiAgICAgICAgICAgICAgICBrZXlpZDo0QjpFMDpCNzo1Njo0RTpGRDozODoxMDpCMDo2Njo2Mzo0NTo2MjoxNzpCRDo0QzpEMjoxMzpFNDo2OQoKICAgIFNpZ25hdHVyZSBBbGdvcml0aG06IHNoYTI1NldpdGhSU0FFbmNyeXB0aW9uCiAgICAgICAgIDFlOjg3OjM2OjcxOjI3OjE2OjNhOjU5OmE2OmJhOjU3Ojc0OjFmOjk4OjgyOmRkOmNhOjM3OgogICAgICAgICA3YTo3Njo4MDoyOTo3NTpmYzo4ZToyMjo0MDoyYjo2NToxYjozNDo5YTpiYTo3ZDo2NjoxMDoKICAgICAgICAgYjk6ZGI6OTY6MTg6NzI6NjQ6Yzk6ZjY6Njg6ZGE6Y2Y6Njk6NWM6ZTg6NTk6NjY6ZGM6Nzc6CiAgICAgICAgIDUzOjNlOjlmOjljOmM4OjBlOmJhOmNlOjc4OjJlOmRkOjBkOjVhOmQ0OjRmOmEyOmU4OmExOgogICAgICAgICBmZjo2NTpiMjo4NzowOTo5Njo4MTo4ZDo2NjpiYzozNToyMDpiZTplNjpiZDo5Mjo3MDplYzoKICAgICAgICAgZGY6ZGQ6NzY6ZDQ6ZDg6NDE6YTI6YWQ6Y2I6ODY6OTI6MjI6ODQ6OGU6YmU6MzE6OGU6Yzc6CiAgICAgICAgIDYxOmZjOmI2OjcwOjJjOmZmOjk4OjE2OjViOmJkOjYzOmEwOjIyOjQ2OjRlOjRkOjAxOmJiOgogICAgICAgICBhYzo1NzpiZjpkZDpkZDpkOToyNDowOTozNDplYTo3Yjo5NToxZTowODphMTozMToxYTo0MDoKICAgICAgICAgY2U6MTc6YmI6MjE6MjM6YWQ6ODQ6N2Q6YjI6MmE6NDQ6MDY6NDY6NTA6Yjk6OWI6OWE6OGY6CiAgICAgICAgIDNmOjNlOjQxOmNhOjNmOjJhOjc4OjcxOjIwOjIzOjllOmU5Ojk2OmE0OjJkOjY4OmY5Ojk5OgogICAgICAgICA4OTo0ZTpkYzpiYjo0Yjo5NjphMDo5NTphMjo0ZDo0ZTo5ODpkNjowNzo1NjpmZDoyNjo0ODoKICAgICAgICAgNGE6ZTU6MGU6YWY6Njg6MzM6MDA6YWU6OTA6NjM6MDI6MzQ6YmQ6MTk6NDE6MTI6MzA6Yzc6CiAgICAgICAgIGY0OmI0OjMzOmQ4OjhhOmRkOjhkOjRmOjY5OjQ2OmY4OjFiOjQ5OmNjOmM4OjFiOmFlOmI3OgogICAgICAgICA4MjplNDphOTo1NTplMDpjYzo2MTo2MTpkNjo0MDoyMTo5MDo1YzpmOTpiNDpjMDo4NDo5MzoKICAgICAgICAgZGM6N2U6OWU6NDU6Yjc6NzQ6NWI6MjQ6NTg6YmY6OTc6YTg6Mjk6NTM6YjU6YmE6OGQ6ZTQ6CiAgICAgICAgIGQxOjhmOmZlOjc5OjcwOjgyOjRmOjMzOjdjOjc1OmQyOjg5OjUwOjQ0OmFiOjU0OjY4OmVlOgogICAgICAgICAzZjphMDo3NDo0YToxZDpjYjoxMjo5YTo1MjplNTo3ZToxMjo0NzoyMDozZTphNzo3MDoxMDoKICAgICAgICAgMWQ6NGQ6YzM6ZmY6YWY6ZWM6ZDI6YmI6NDA6NTE6Yjc6Yjc6NmY6MDU6NTE6MWI6MmU6ZGE6CiAgICAgICAgIDBiOjA1OjhjOmVlOmU0OjhiOjQ4OjJlOjIwOmNiOjZlOmJkOjZhOjA0OjE5OjAzOjQxOjdkOgogICAgICAgICBhNzo2MTozOTo4ZDowMzpmNzpiODo0YjpmYzowOTplMjphMzoyMzozNjpjNDozNjo1NTo3YzoKICAgICAgICAgMzI6OTQ6MTg6ODY6Mzg6MTc6YzA6NmQ6Nzk6MGY6ZTQ6MjM6ODc6NWY6NWU6M2I6NjM6M2M6CiAgICAgICAgIGZkOmMwOjA5Ojg1OmU1OjViOjMxOmY0Ojk4OmI0OjdiOmU3OjYzOjk5OmJjOmY5OjI1OjIyOgogICAgICAgICBmOTo2MDoyYjpkZTo1ZDplMjo5NDo1MjozNzo3MTpjNjo4MDoyMTpmNjo2MDoxZjpiZjo0MToKICAgICAgICAgOGU6ZGM6NTY6MzM6NTA6ZWI6YWY6MTU6Nzg6OTg6Mjk6ZTI6OTQ6ODU6Yzg6YWY6MTM6YzY6CiAgICAgICAgIDFiOjk1OjBjOmMyOjc1OjA3OmY0OmE1OmQyOjVhOjVmOjAwOmQ0OmJiOmE0OmU5OmFhOmYyOgogICAgICAgICA0MDpkNjplZTo4YzowMjowMDpiMzo1Yjo1YTpmNTpmMTowYjpjOTpiOTo2NDpiNjpiNDo2ODoKICAgICAgICAgODY6MzQ6MWU6OWM6ZjA6NDM6YjI6ZDY6YmU6YTU6NDU6NDc6N2E6OWM6MDA6Zjk6YzA6MGY6CiAgICAgICAgIDRjOjMyOjNjOjM0OjM5OjIyOjM1Ojk0OjM1OjUxOjc4OmY0OjhjOjA2OjFlOmIwOjI2OmFlOgogICAgICAgICA5ZDpmZDozZToyZjo2ZTowNTo1YTo2MwotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRTVEQ0NBc3lnQXdJQkFnSUNBSmt3RFFZSktvWklodmNOQVFFTEJRQXdnWUF4Q3pBSkJnTlZCQVlUQWtsTwpNUkl3RUFZRFZRUUlEQWxVWld4aGJtZGhibUV4RWpBUUJnTlZCQWNNQ1VoNVpHVnlZV0poWkRFWE1CVUdBMVVFCkNnd09iMjVsWTI5dWRtVnlaMlZ1WTJVeERqQU1CZ05WQkFNTUJXUnJkV0psTVF3d0NnWURWUVFMREFOT2FXd3gKRWpBUUJna3Foa2lHOXcwQkNRRVdBMDVwYkRBZUZ3MHhPVEEwTURNeE1URTBNREJhRncweU1EQTBNREl4TVRFMApNREJhTUd3eEN6QUpCZ05WQkFZVEFrbE9NUkl3RUFZRFZRUUlEQWxVWld4aGJtZGhibUV4RnpBVkJnTlZCQW9NCkRtOXVaV052Ym5abGNtZGxibU5sTVF3d0NnWURWUVFMREFOT2FXd3hEakFNQmdOVkJBTU1CV1JyZFdKbE1SSXcKRUFZSktvWklodmNOQVFrQkZnTk9hV3d3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQgpBUURnVmZQQ3BwV2J5WWNtRkRLdFFJd0JCQmZ5SkxqWjNDNGVxazQ3bC9zdlZVYUQ5SlNkVk9KUVZXenY5amxXCkhVajdQWUtLN3hGOXFtMVFLcUErTU4ycWJXUWsrcVNKU2NoV3dXQ29MRnBTcE5XMnM2NnVnRnovSThmaXRZNloKK3gxUUZYbXZZcTU0TExYN09oYjkzcnVyRjVrYVMzNTRVcEQ0REhOd29RdGxTazJqSDdzdTFjVVptRTBiZ016RwpMaHVaSEtlTkFQK3g2RmU3K2w1UHprL2thczlDYUF5SzZvbjIvem5WZktjNlQ0RlNRbmM3UlVTeHJ5bkgwRnVTCngyUFVLQ0hXMG9nVWpoVjhvc293M2dZbWEvQ3FNakpiTUZMNmJLQTA1a2NJQWFkOXMwL0lTSG1PN2VteDJVT1UKakViWUVoaStHQjRuQjhnQU1GbTM1YktUQWdNQkFBR2plekI1TUFrR0ExVWRFd1FDTUFBd0xBWUpZSVpJQVliNApRZ0VOQkI4V0hVOXdaVzVUVTB3Z1IyVnVaWEpoZEdWa0lFTmxjblJwWm1sallYUmxNQjBHQTFVZERnUVdCQlI5CnNXK1VPM2Y0Z1IvSm5PcFFNYzlPV0hHekN6QWZCZ05WSFNNRUdEQVdnQlJMNExkV1R2MDRFTEJtWTBWaUY3MU0KMGhQa2FUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFIb2MyY1NjV09sbW11bGQwSDVpQzNjbzNlbmFBS1hYOApqaUpBSzJVYk5KcTZmV1lRdWR1V0dISmt5ZlpvMnM5cFhPaFpadHgzVXo2Zm5NZ091czU0THQwTld0UlBvdWloCi8yV3lod21XZ1kxbXZEVWd2dWE5a25EczM5MTIxTmhCb3EzTGhwSWloSTYrTVk3SFlmeTJjQ3ovbUJaYnZXT2cKSWtaT1RRRzdyRmUvM2QzWkpBazA2bnVWSGdpaE1ScEF6aGU3SVNPdGhIMnlLa1FHUmxDNW01cVBQejVCeWo4cQplSEVnSTU3cGxxUXRhUG1aaVU3Y3UwdVdvSldpVFU2WTFnZFcvU1pJU3VVT3IyZ3pBSzZRWXdJMHZSbEJFakRICjlMUXoySXJkalU5cFJ2Z2JTY3pJRzY2M2d1U3BWZURNWVdIV1FDR1FYUG0wd0lTVDNINmVSYmQwV3lSWXY1ZW8KS1ZPMXVvM2swWS8rZVhDQ1R6TjhkZEtKVUVTclZHanVQNkIwU2gzTEVwcFM1WDRTUnlBK3AzQVFIVTNELzYvcwowcnRBVWJlM2J3VlJHeTdhQ3dXTTd1U0xTQzRneTI2OWFnUVpBMEY5cDJFNWpRUDN1RXY4Q2VLakl6YkVObFY4Ck1wUVloamdYd0cxNUQrUWpoMTllTzJNOC9jQUpoZVZiTWZTWXRIdm5ZNW04K1NVaStXQXIzbDNpbEZJM2NjYUEKSWZaZ0g3OUJqdHhXTTFEcnJ4VjRtQ25pbElYSXJ4UEdHNVVNd25VSDlLWFNXbDhBMUx1azZhcnlRTmJ1akFJQQpzMXRhOWZFTHlibGt0clJvaGpRZW5QQkRzdGErcFVWSGVwd0ErY0FQVERJOE5Ea2lOWlExVVhqMGpBWWVzQ2F1Cm5mMCtMMjRGV21NPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNEZYendxYVZtOG1ISmhReXJVQ01BUVFYOGlTNDJkd3VIcXBPTzVmN0wxVkdnL1NVCm5WVGlVRlZzNy9ZNVZoMUkrejJDaXU4UmZhcHRVQ3FnUGpEZHFtMWtKUHFraVVuSVZzRmdxQ3hhVXFUVnRyT3UKcm9CYy95UEg0cldPbWZzZFVCVjVyMkt1ZUN5MSt6b1cvZDY3cXhlWkdrdCtlRktRK0F4emNLRUxaVXBOb3grNwpMdFhGR1poTkc0RE14aTRibVJ5bmpRRC9zZWhYdS9wZVQ4NVA1R3JQUW1nTWl1cUo5djg1MVh5bk9rK0JVa0ozCk8wVkVzYThweDlCYmtzZGoxQ2doMXRLSUZJNFZmS0xLTU40R0ptdndxakl5V3pCUytteWdOT1pIQ0FHbmZiTlAKeUVoNWp1M3BzZGxEbEl4RzJCSVl2aGdlSndmSUFEQlp0K1d5a3dJREFRQUJBb0lCQVFDbjFBV3gyTGhTUFBsTApwbzZuQ0lQMCtxQURlaStFWlBGbjVaYnpoR2JaYVYyQXVJZzZEOWZqcTVUOURHS21wdkFEYldmdEVwOHVPVUxnClY1TmNFMml4Nkhha0o1TFNWbzEzUWVKU3ppT2dja3FrRFZhZ204MTIzc2phTldPQ2xOZkFJdURQTWU4K1hveWkKYnpubUlTeWErZU9EUlhsUEFNNE5sQnNFNXFaRTFtUFpxRFhCdCtHUWRkT09ZQXFzNCtFdklZRmc4QmNVRVhSSAppd1d3MkRZMmFXbWNnRXdoVElMRk03dElrY3VHYjhTakFNVDdRdm9CWWNleFM1Z0R0emN5emNjWVIzSmxoWkZ1Cm8zUWZ2RHExb1l5UmYyeG5nNE52ZzhtaUpmQkJ1TkI4Z1pZMXpTSlhjeFVqUFJEQVowMUplemRJRkNXOXlBNFMKTmNMUkE4TTVBb0dCQVBrbCtWaGFjL3VrUUUwS1ErOGpycnlHa1FPbWNzaFVMdSt0NHZicHJBU1VkQThoenlGZAoySVFMM2g4QzJTVU5VRDBYakhRY2V5VzNlTW1Fc2svYzd1WDJjUHRQdnNGRVorcW9VandxbUYzN1V5VXNXVkJZCjlqUDQwTXo2S25RQ04wdHRPUzBodlo1RTRYajlrUW1zNCtCK0htckpEU0x3U1NHS3MvK3A4K3czQW9HQkFPYUIKUzZETmd6UFNYR2JkZlpXeDFjcFY2ZUR0RHhjODdscllUSXAyRzFMRlBtSDhaeS9PNk5qSDdlS3lTQUlaVGtLOAp1aGhzWlRuOFhyWUFuR1E4ei9zeCtuOGp4TVNoZGFNaWNXeTdXOXgzZEFoWGJ2T2NRT2RyU3p0bTQxa2kwNGhVCmFEamk3OEVSem9McUw5SklwbmJiZTFLQXVvL3ZjcFNYQkxsaCt0YUZBb0dBVjFMaDgvK3dDeERrb0p2cWQ1U3cKRjgrcVgvY2szK1h4bFh3Q3dydmYyTE1YZ240OUZOckptbTUyYWJRYjI0cXhCdGlNRjk0cm8ycU00VVNySXFheQo3TkxWZ3AvT29mcVIyWU1wWDRFbWFqbytTQmNsTHE0ZmpOTzJpMEZiUTlITEE1ckNvWGpqOXViNWgraUh2elpqCm9EbFQrK1YvdnpFczBKN0d1K01iWlQwQ2dZRUF5bmc3MUExdzk2NEptQmxwM0htT3p1SFVROHcyK3pSOE1iUFkKMTY2U3BZdTRGaDI5RFpOem1DZFZYMUUyU3hHcldwZW41eGdmZW1XaFU4RUpua3FFYmFNaTQxYXAyZ1h3N05DdQpUTkh1Q0tPc2VqOUNxQjFTTFhSamF0UWZVd1p5UkVmUUhGZktQUTdGRk4xY0VCdmNqSDZSdnBCd1Qwb0duVnBoCnZlekFobmtDZ1lFQWgwMGVwWW9WVjc0aFpzZUo4cTF1bmFha3NVc3ZEUXE5SlpObFdSUUFSQUVUbXYvdm5GcmUKVHhRckxXaXhITWZjUlRZaFZaSWdRcXNCZ3N4MmgyZXVGSStLRE4zUStaMW5KMUZLZ1g0Z2NHV3pXdlludkd6cwpOK1J2NTV3MnVTZWYxMS9sYzlYUEVMbXlDWkpBTkM4aStYMG96eHgxNWJ6RzBuZFFKcGNPaXd3PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: dkube-certificate-secret
  namespace: dkube-tools
type: kubernetes.io/tls
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: service
    service: ambassador-admin
  name: ambassador-admin
  namespace: dkube-tools
spec:
  ports:
  - name: ambassador-admin
    port: 8877
    protocol: TCP
    targetPort: 8877
  selector:
    service: ambassador
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          secret: dkube-certificate-secret
  labels:
    service: ambassador
  name: ambassador
  namespace: dkube-tools
spec:
  ports:
  - name: ambassador
    nodePort: 32333
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    service: ambassador
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  dkube_installer
      prefix: /installer
      rewrite: /ui
      timeout_ms: 600000
      service: dkube-installer-service.kube-system:8888
      cors:
       origins: "*"
       methods: "*"
       headers: "*"
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  dkube_installer_report
      prefix: /report
      rewrite: /report
      timeout_ms: 600000
      service: dkube-installer-service.kube-system:8888
      cors:
       origins: "*"
       methods: "*"
       headers: "*"
  name: dkube-installer
  namespace: dkube-tools
spec:
  ports:
  - name: serve
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    role: dkube-installer
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ambassador
  namespace: dkube-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ambassador
subjects:
- kind: ServiceAccount
  name: ambassador
  namespace: dkube-tools
